apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: asekt
  namespace: asekt
spec:
  rules:
  - host: ec2-54-81-13-249.compute-1.amazonaws.com
    http:
      paths:
      - path: /ASEKTConfiguracion-0.0.1-SNAPSHOT
        backend:
          serviceName: msasekt
          servicePort: 80
      - path: /
        backend:
          serviceName: frontasekt
          servicePort: 80

