apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: msdemo
  namespace: dev
spec:
  rules:
  - host: ec2-3-226-254-132.compute-1.amazonaws.com
    http:
      paths:
      - path: /mads-todolist-inicial-1.0.0
        backend:
          serviceName: msdemo
          servicePort: 80
