pipeline {
    agent any

   stages {
        stage('Build'){
            steps {
               withSonarQubeEnv('Sonarqube') {
                    echo '####################### BUILDING ASEKT'
                    dir ('mads-todolist-inicial') {
                        script {
                        //status = sh (returnStatus: true, script: 'mvn clean package -DistTest')
                        status = sh (returnStatus: true, script: 'mvn clean package -DistTest sonar:sonar \
  -Dsonar.projectKey=demo \
  -Dsonar.host.url=http://ec2-3-235-29-59.compute-1.amazonaws.com:9000 \
  -Dsonar.login=471685943f484024fb3437d74f97dd653a116016')
                        echo "******************************************************************** Status:  ${status} "
                        if (status == 0) {
				sh ' echo VAMOS'
                script{
                    timeout(time: 10, unit: 'MINUTES') {
                        def qg = waitForQualityGate abortPipeline: true
                        if (qg.status != 'OK') {
                            echo "Status: ${qg.status}"
                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
                        }
                    }
                }
                        }
                        }
                    }
               }
            }
       }
   }
   post {
        always {
            echo 'One way or another, I have finished'
        }
        success {
            echo 'I succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things were different before...'
        }
    }
}

