apiVersion: v1
kind: Service
metadata:
  name: mscambiofisico
  namespace: desarrollo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    name: mscambiofisico

